"""add intensity_duration_minutes to fsm_event

Revision ID: 4d952e1a0afb
Revises: 4c7c81d9ad14
Create Date: 2025-12-18 15:43:59.871647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d952e1a0afb'
down_revision: Union[str, Sequence[str], None] = '4c7c81d9ad14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fsm_event', sa.Column('intensity_duration_minutes', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fsm_event', 'intensity_duration_minutes')
    # ### end Alembic commands ###
