"""Add visit table

Revision ID: 651697a832a7
Revises: 63d374d08e35
Create Date: 2025-11-23 14:04:29.909158

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '651697a832a7'
down_revision: Union[str, Sequence[str], None] = '63d374d08e35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('visit',
    sa.Column('install_id', sa.Integer(), nullable=False),
    sa.Column('visit_date', sa.DateTime(), nullable=False),
    sa.Column('crew_lead', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('silt_level_mm', sa.Integer(), nullable=True),
    sa.Column('battery_voltage', sa.Float(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('photos_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['install_id'], ['install.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('visit')
    # ### end Alembic commands ###
