"""Initial schema

Revision ID: 68650b2a5b67
Revises: 
Create Date: 2025-12-12 14:25:52.794988

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '68650b2a5b67'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attachment',
    sa.Column('filename', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('file_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('note_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('monitor_id', sa.Integer(), nullable=True),
    sa.Column('install_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('note',
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('monitor_id', sa.Integer(), nullable=True),
    sa.Column('install_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('access_fsm', sa.Boolean(), nullable=False),
    sa.Column('access_fsa', sa.Boolean(), nullable=False),
    sa.Column('access_wq', sa.Boolean(), nullable=False),
    sa.Column('access_verification', sa.Boolean(), nullable=False),
    sa.Column('access_ssd', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('fsaproject',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('job_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('client', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fsaproject_job_number'), 'fsaproject', ['job_number'], unique=False)
    op.create_index(op.f('ix_fsaproject_name'), 'fsaproject', ['name'], unique=False)
    op.create_table('fsmproject',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('job_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('client', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('client_job_ref', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('survey_start_date', sa.DateTime(), nullable=True),
    sa.Column('survey_end_date', sa.DateTime(), nullable=True),
    sa.Column('survey_complete', sa.Boolean(), nullable=False),
    sa.Column('default_download_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('last_ingestion_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fsmproject_job_number'), 'fsmproject', ['job_number'], unique=False)
    op.create_index(op.f('ix_fsmproject_name'), 'fsmproject', ['name'], unique=False)
    op.create_table('verificationproject',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('job_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('client', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('model_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verificationproject_job_number'), 'verificationproject', ['job_number'], unique=False)
    op.create_index(op.f('ix_verificationproject_name'), 'verificationproject', ['name'], unique=False)
    op.create_table('waterqualityproject',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('job_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('client', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('campaign_date', sa.DateTime(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_waterqualityproject_job_number'), 'waterqualityproject', ['job_number'], unique=False)
    op.create_index(op.f('ix_waterqualityproject_name'), 'waterqualityproject', ['name'], unique=False)
    op.create_table('fsadataset',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('variable', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('file_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('imported_at', sa.DateTime(), nullable=False),
    sa.Column('metadata_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['fsaproject.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fsaprojectcollaborator',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['fsaproject.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('project_id', 'user_id')
    )
    op.create_table('fsmevent',
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('event_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('total_rainfall_mm', sa.Float(), nullable=True),
    sa.Column('max_intensity_mm_hr', sa.Float(), nullable=True),
    sa.Column('preceding_dry_hours', sa.Float(), nullable=True),
    sa.Column('reviewed', sa.Boolean(), nullable=False),
    sa.Column('review_comment', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('reviewed_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['fsmproject.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fsmevent_project_id'), 'fsmevent', ['project_id'], unique=False)
    op.create_table('monitor',
    sa.Column('monitor_asset_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('monitor_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('monitor_sub_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('pmac_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['fsmproject.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monitor_monitor_asset_id'), 'monitor', ['monitor_asset_id'], unique=True)
    op.create_table('projectcollaborator',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['fsmproject.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('project_id', 'user_id')
    )
    op.create_table('site',
    sa.Column('site_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('site_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('mh_ref', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('w3w', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('easting', sa.Float(), nullable=False),
    sa.Column('northing', sa.Float(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['fsmproject.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_site_site_id'), 'site', ['site_id'], unique=False)
    op.create_table('surveyevent',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['fsaproject.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('toleranceset',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('event_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('for_critical', sa.Boolean(), nullable=False),
    sa.Column('for_surcharged', sa.Boolean(), nullable=False),
    sa.Column('depth_time_tolerance_hrs', sa.Float(), nullable=False),
    sa.Column('depth_peak_tolerance_pct', sa.Float(), nullable=False),
    sa.Column('depth_peak_tolerance_abs_m', sa.Float(), nullable=False),
    sa.Column('depth_peak_surcharged_upper_m', sa.Float(), nullable=False),
    sa.Column('depth_peak_surcharged_lower_m', sa.Float(), nullable=False),
    sa.Column('flow_nse_threshold', sa.Float(), nullable=False),
    sa.Column('flow_time_tolerance_hrs', sa.Float(), nullable=False),
    sa.Column('flow_peak_tolerance_upper_pct', sa.Float(), nullable=False),
    sa.Column('flow_peak_tolerance_lower_pct', sa.Float(), nullable=False),
    sa.Column('flow_volume_tolerance_upper_pct', sa.Float(), nullable=False),
    sa.Column('flow_volume_tolerance_lower_pct', sa.Float(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['verificationproject.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_toleranceset_name'), 'toleranceset', ['name'], unique=False)
    op.create_index(op.f('ix_toleranceset_project_id'), 'toleranceset', ['project_id'], unique=False)
    op.create_table('verificationevent',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('event_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['verificationproject.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verificationevent_name'), 'verificationevent', ['name'], unique=False)
    op.create_index(op.f('ix_verificationevent_project_id'), 'verificationevent', ['project_id'], unique=False)
    op.create_table('verificationflowmonitor',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('icm_node_reference', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_critical', sa.Boolean(), nullable=False),
    sa.Column('is_surcharged', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['verificationproject.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verificationflowmonitor_name'), 'verificationflowmonitor', ['name'], unique=False)
    op.create_index(op.f('ix_verificationflowmonitor_project_id'), 'verificationflowmonitor', ['project_id'], unique=False)
    op.create_table('verificationprojectcollaborator',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['verificationproject.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('project_id', 'user_id')
    )
    op.create_table('waterqualitydataset',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('file_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('original_filename', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('upload_date', sa.DateTime(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['waterqualityproject.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wqmonitor',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('location_x', sa.Float(), nullable=True),
    sa.Column('location_y', sa.Float(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['waterqualityproject.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wqprojectcollaborator',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['waterqualityproject.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('project_id', 'user_id')
    )
    op.create_table('flowmonitor',
    sa.Column('dataset_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('timestep_minutes', sa.Float(), nullable=False),
    sa.Column('flow_units', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('depth_units', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('velocity_units', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('x', sa.Float(), nullable=True),
    sa.Column('y', sa.Float(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['fsadataset.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fsatimeseries',
    sa.Column('dataset_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('flow', sa.Float(), nullable=True),
    sa.Column('depth', sa.Float(), nullable=True),
    sa.Column('velocity', sa.Float(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['fsadataset.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fsatimeseries_dataset_id'), 'fsatimeseries', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_fsatimeseries_timestamp'), 'fsatimeseries', ['timestamp'], unique=False)
    op.create_table('install',
    sa.Column('install_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('install_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('client_ref', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('install_date', sa.DateTime(), nullable=True),
    sa.Column('remove_date', sa.DateTime(), nullable=True),
    sa.Column('fm_pipe_letter', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('fm_pipe_shape', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('fm_pipe_height_mm', sa.Integer(), nullable=False),
    sa.Column('fm_pipe_width_mm', sa.Integer(), nullable=False),
    sa.Column('fm_pipe_depth_to_invert_mm', sa.Integer(), nullable=False),
    sa.Column('fm_sensor_offset_mm', sa.Integer(), nullable=False),
    sa.Column('rg_position', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('monitor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['monitor_id'], ['monitor.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['fsmproject.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['site.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_install_install_id'), 'install', ['install_id'], unique=False)
    op.create_table('raingauge',
    sa.Column('dataset_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('timestep_minutes', sa.Float(), nullable=False),
    sa.Column('x', sa.Float(), nullable=True),
    sa.Column('y', sa.Float(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['fsadataset.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('traceset',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_file', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('imported_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['verificationevent.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_traceset_event_id'), 'traceset', ['event_id'], unique=False)
    op.create_index(op.f('ix_traceset_name'), 'traceset', ['name'], unique=False)
    op.create_table('wqtimeseries',
    sa.Column('monitor_id', sa.Integer(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=False),
    sa.Column('variable', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('unit', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('filename', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['waterqualitydataset.id'], ),
    sa.ForeignKeyConstraint(['monitor_id'], ['wqmonitor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event',
    sa.Column('install_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('label', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['install_id'], ['install.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('flowmonitormodel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('monitor_id', sa.Integer(), nullable=False),
    sa.Column('has_model_data', sa.Boolean(), nullable=False),
    sa.Column('pipe_ref', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('model_rg', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('pipe_length', sa.Float(), nullable=True),
    sa.Column('pipe_shape', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('pipe_dia', sa.Float(), nullable=True),
    sa.Column('pipe_height', sa.Float(), nullable=True),
    sa.Column('pipe_roughness', sa.Float(), nullable=True),
    sa.Column('us_invert', sa.Float(), nullable=True),
    sa.Column('ds_invert', sa.Float(), nullable=True),
    sa.Column('system_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['monitor_id'], ['flowmonitor.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('monitor_id')
    )
    op.create_table('flowmonitorstats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('monitor_id', sa.Integer(), nullable=False),
    sa.Column('min_flow', sa.Float(), nullable=True),
    sa.Column('max_flow', sa.Float(), nullable=True),
    sa.Column('total_volume', sa.Float(), nullable=True),
    sa.Column('min_depth', sa.Float(), nullable=True),
    sa.Column('max_depth', sa.Float(), nullable=True),
    sa.Column('min_velocity', sa.Float(), nullable=True),
    sa.Column('max_velocity', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['monitor_id'], ['flowmonitor.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('monitor_id')
    )
    op.create_table('monitortraceversion',
    sa.Column('timestep_minutes', sa.Integer(), nullable=False),
    sa.Column('upstream_end', sa.Boolean(), nullable=False),
    sa.Column('obs_location_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('pred_location_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trace_set_id', sa.Integer(), nullable=False),
    sa.Column('monitor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['monitor_id'], ['verificationflowmonitor.id'], ),
    sa.ForeignKeyConstraint(['trace_set_id'], ['traceset.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monitortraceversion_monitor_id'), 'monitortraceversion', ['monitor_id'], unique=False)
    op.create_index(op.f('ix_monitortraceversion_trace_set_id'), 'monitortraceversion', ['trace_set_id'], unique=False)
    op.create_table('raingaugestats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rain_gauge_id', sa.Integer(), nullable=False),
    sa.Column('min_intensity', sa.Float(), nullable=True),
    sa.Column('max_intensity', sa.Float(), nullable=True),
    sa.Column('total_depth', sa.Float(), nullable=True),
    sa.Column('return_period', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['rain_gauge_id'], ['raingauge.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rain_gauge_id')
    )
    op.create_table('rawdatasettings',
    sa.Column('install_id', sa.Integer(), nullable=False),
    sa.Column('file_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('rainfall_file_format', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('depth_file_format', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('velocity_file_format', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('battery_file_format', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('pumplogger_file_format', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('rg_tb_depth', sa.Float(), nullable=True),
    sa.Column('rg_timing_corr', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('pipe_shape', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('pipe_width', sa.Integer(), nullable=True),
    sa.Column('pipe_height', sa.Integer(), nullable=True),
    sa.Column('pipe_shape_intervals', sa.Integer(), nullable=True),
    sa.Column('pipe_shape_def', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('dep_corr', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('vel_corr', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('dv_timing_corr', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('silt_levels', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('pl_timing_corr', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('pl_added_onoffs', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['install_id'], ['install.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('install_id')
    )
    op.create_table('timeseries',
    sa.Column('install_id', sa.Integer(), nullable=True),
    sa.Column('monitor_id', sa.Integer(), nullable=True),
    sa.Column('variable', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('data_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('interval_minutes', sa.Integer(), nullable=False),
    sa.Column('filename', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('unit', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['install_id'], ['install.id'], ),
    sa.ForeignKeyConstraint(['monitor_id'], ['monitor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('visit',
    sa.Column('install_id', sa.Integer(), nullable=False),
    sa.Column('visit_date', sa.DateTime(), nullable=False),
    sa.Column('crew_lead', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('silt_level_mm', sa.Integer(), nullable=True),
    sa.Column('battery_voltage', sa.Float(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('photos_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['install_id'], ['install.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('verificationrun',
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_final_for_monitor_event', sa.Boolean(), nullable=False),
    sa.Column('overall_flow_score', sa.Float(), nullable=True),
    sa.Column('overall_depth_score', sa.Float(), nullable=True),
    sa.Column('overall_status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('nse', sa.Float(), nullable=True),
    sa.Column('kge', sa.Float(), nullable=True),
    sa.Column('cv_obs', sa.Float(), nullable=True),
    sa.Column('analysis_settings', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('monitor_trace_id', sa.Integer(), nullable=False),
    sa.Column('tolerance_set_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('finalized_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['monitor_trace_id'], ['monitortraceversion.id'], ),
    sa.ForeignKeyConstraint(['tolerance_set_id'], ['toleranceset.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verificationrun_monitor_trace_id'), 'verificationrun', ['monitor_trace_id'], unique=False)
    op.create_table('verificationtimeseries',
    sa.Column('series_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('parquet_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('record_count', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('monitor_trace_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['monitor_trace_id'], ['monitortraceversion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verificationtimeseries_monitor_trace_id'), 'verificationtimeseries', ['monitor_trace_id'], unique=False)
    op.create_table('manualadjustment',
    sa.Column('adjustment_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('parameter', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['verificationrun.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_manualadjustment_run_id'), 'manualadjustment', ['run_id'], unique=False)
    op.create_table('verificationmetric',
    sa.Column('parameter', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('metric_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('score_band', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('score_points', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['verificationrun.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verificationmetric_run_id'), 'verificationmetric', ['run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_verificationmetric_run_id'), table_name='verificationmetric')
    op.drop_table('verificationmetric')
    op.drop_index(op.f('ix_manualadjustment_run_id'), table_name='manualadjustment')
    op.drop_table('manualadjustment')
    op.drop_index(op.f('ix_verificationtimeseries_monitor_trace_id'), table_name='verificationtimeseries')
    op.drop_table('verificationtimeseries')
    op.drop_index(op.f('ix_verificationrun_monitor_trace_id'), table_name='verificationrun')
    op.drop_table('verificationrun')
    op.drop_table('visit')
    op.drop_table('timeseries')
    op.drop_table('rawdatasettings')
    op.drop_table('raingaugestats')
    op.drop_index(op.f('ix_monitortraceversion_trace_set_id'), table_name='monitortraceversion')
    op.drop_index(op.f('ix_monitortraceversion_monitor_id'), table_name='monitortraceversion')
    op.drop_table('monitortraceversion')
    op.drop_table('flowmonitorstats')
    op.drop_table('flowmonitormodel')
    op.drop_table('event')
    op.drop_table('wqtimeseries')
    op.drop_index(op.f('ix_traceset_name'), table_name='traceset')
    op.drop_index(op.f('ix_traceset_event_id'), table_name='traceset')
    op.drop_table('traceset')
    op.drop_table('raingauge')
    op.drop_index(op.f('ix_install_install_id'), table_name='install')
    op.drop_table('install')
    op.drop_index(op.f('ix_fsatimeseries_timestamp'), table_name='fsatimeseries')
    op.drop_index(op.f('ix_fsatimeseries_dataset_id'), table_name='fsatimeseries')
    op.drop_table('fsatimeseries')
    op.drop_table('flowmonitor')
    op.drop_table('wqprojectcollaborator')
    op.drop_table('wqmonitor')
    op.drop_table('waterqualitydataset')
    op.drop_table('verificationprojectcollaborator')
    op.drop_index(op.f('ix_verificationflowmonitor_project_id'), table_name='verificationflowmonitor')
    op.drop_index(op.f('ix_verificationflowmonitor_name'), table_name='verificationflowmonitor')
    op.drop_table('verificationflowmonitor')
    op.drop_index(op.f('ix_verificationevent_project_id'), table_name='verificationevent')
    op.drop_index(op.f('ix_verificationevent_name'), table_name='verificationevent')
    op.drop_table('verificationevent')
    op.drop_index(op.f('ix_toleranceset_project_id'), table_name='toleranceset')
    op.drop_index(op.f('ix_toleranceset_name'), table_name='toleranceset')
    op.drop_table('toleranceset')
    op.drop_table('surveyevent')
    op.drop_index(op.f('ix_site_site_id'), table_name='site')
    op.drop_table('site')
    op.drop_table('projectcollaborator')
    op.drop_index(op.f('ix_monitor_monitor_asset_id'), table_name='monitor')
    op.drop_table('monitor')
    op.drop_index(op.f('ix_fsmevent_project_id'), table_name='fsmevent')
    op.drop_table('fsmevent')
    op.drop_table('fsaprojectcollaborator')
    op.drop_table('fsadataset')
    op.drop_index(op.f('ix_waterqualityproject_name'), table_name='waterqualityproject')
    op.drop_index(op.f('ix_waterqualityproject_job_number'), table_name='waterqualityproject')
    op.drop_table('waterqualityproject')
    op.drop_index(op.f('ix_verificationproject_name'), table_name='verificationproject')
    op.drop_index(op.f('ix_verificationproject_job_number'), table_name='verificationproject')
    op.drop_table('verificationproject')
    op.drop_index(op.f('ix_fsmproject_name'), table_name='fsmproject')
    op.drop_index(op.f('ix_fsmproject_job_number'), table_name='fsmproject')
    op.drop_table('fsmproject')
    op.drop_index(op.f('ix_fsaproject_name'), table_name='fsaproject')
    op.drop_index(op.f('ix_fsaproject_job_number'), table_name='fsaproject')
    op.drop_table('fsaproject')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_table('user')
    op.drop_table('note')
    op.drop_table('attachment')
    # ### end Alembic commands ###
