"""Add monitor_id to timeseries

Revision ID: 6a998ea89017
Revises: c87ff3a1090a
Create Date: 2025-11-23 15:30:57.080192

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6a998ea89017'
down_revision: Union[str, Sequence[str], None] = 'c87ff3a1090a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('timeseries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('monitor_id', sa.Integer(), nullable=True))
        batch_op.alter_column('install_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_foreign_key('fk_timeseries_monitor_id_monitor', 'monitor', ['monitor_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('timeseries', schema=None) as batch_op:
        batch_op.drop_constraint('fk_timeseries_monitor_id_monitor', type_='foreignkey')
        batch_op.alter_column('install_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('monitor_id')
    # ### end Alembic commands ###
