"""Initial migration

Revision ID: 9e9c7c437291
Revises: 
Create Date: 2025-11-23 13:44:59.468204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9e9c7c437291'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monitor',
    sa.Column('monitor_asset_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('monitor_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('monitor_sub_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('pmac_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monitor_monitor_asset_id'), 'monitor', ['monitor_asset_id'], unique=True)
    op.create_table('project',
    sa.Column('job_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('job_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('client', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('client_job_ref', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('survey_start_date', sa.DateTime(), nullable=True),
    sa.Column('survey_end_date', sa.DateTime(), nullable=True),
    sa.Column('survey_complete', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_job_number'), 'project', ['job_number'], unique=False)
    op.create_table('site',
    sa.Column('site_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('site_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('mh_ref', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('w3w', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('easting', sa.Float(), nullable=False),
    sa.Column('northing', sa.Float(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_site_site_id'), 'site', ['site_id'], unique=False)
    op.create_table('install',
    sa.Column('install_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('install_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('client_ref', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('install_date', sa.DateTime(), nullable=True),
    sa.Column('remove_date', sa.DateTime(), nullable=True),
    sa.Column('fm_pipe_letter', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('fm_pipe_shape', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('fm_pipe_height_mm', sa.Integer(), nullable=False),
    sa.Column('fm_pipe_width_mm', sa.Integer(), nullable=False),
    sa.Column('fm_pipe_depth_to_invert_mm', sa.Integer(), nullable=False),
    sa.Column('fm_sensor_offset_mm', sa.Integer(), nullable=False),
    sa.Column('rg_position', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('monitor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['monitor_id'], ['monitor.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['site.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_install_install_id'), 'install', ['install_id'], unique=False)
    op.create_table('event',
    sa.Column('install_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('label', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['install_id'], ['install.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('timeseries',
    sa.Column('install_id', sa.Integer(), nullable=False),
    sa.Column('variable', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('data_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('interval_minutes', sa.Integer(), nullable=False),
    sa.Column('filename', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['install_id'], ['install.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('timeseries')
    op.drop_table('event')
    op.drop_index(op.f('ix_install_install_id'), table_name='install')
    op.drop_table('install')
    op.drop_index(op.f('ix_site_site_id'), table_name='site')
    op.drop_table('site')
    op.drop_index(op.f('ix_project_job_number'), table_name='project')
    op.drop_table('project')
    op.drop_index(op.f('ix_monitor_monitor_asset_id'), table_name='monitor')
    op.drop_table('monitor')
    # ### end Alembic commands ###
