"""add unit to timeseries

Revision ID: a5d829c8b2e1
Revises: b4e38e0171e7
Create Date: 2025-12-05 21:18:53.506062

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5d829c8b2e1'
down_revision: Union[str, Sequence[str], None] = 'b4e38e0171e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('timeseries', sa.Column('unit', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('timeseries', 'unit')
    # ### end Alembic commands ###
