"""Add FSM models

Revision ID: b4e38e0171e7
Revises: f00f6e5349a9
Create Date: 2025-11-27 08:21:41.818776

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b4e38e0171e7'
down_revision: Union[str, Sequence[str], None] = 'f00f6e5349a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interim',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('data_import_complete', sa.Boolean(), nullable=False),
    sa.Column('site_inspection_review_complete', sa.Boolean(), nullable=False),
    sa.Column('data_classification_complete', sa.Boolean(), nullable=False),
    sa.Column('report_complete', sa.Boolean(), nullable=False),
    sa.Column('summary_text', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('interimreview',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('interim_id', sa.Integer(), nullable=False),
    sa.Column('install_id', sa.Integer(), nullable=False),
    sa.Column('data_covered', sa.Boolean(), nullable=False),
    sa.Column('ignore_missing', sa.Boolean(), nullable=False),
    sa.Column('reason_missing', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('anomalies_found', sa.Boolean(), nullable=False),
    sa.Column('comments', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['install_id'], ['install.id'], ),
    sa.ForeignKeyConstraint(['interim_id'], ['interim.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('processeddata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('install_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('file_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['install_id'], ['install.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rawdata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('install_id', sa.Integer(), nullable=False),
    sa.Column('rainfall_file_pattern', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('depth_file_pattern', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('velocity_file_pattern', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('silt_levels_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('depth_corrections_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('velocity_corrections_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('pipe_shape_override', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['install_id'], ['install.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('install_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rawdata')
    op.drop_table('processeddata')
    op.drop_table('interimreview')
    op.drop_table('interim')
    # ### end Alembic commands ###
