# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Fergus.Graham\OneDrive - Tetra Tech, Inc\vscode\flowbot_04032024\FlowBot\ui_elements\ui_flowbot_dialog_fsm_remove_data_base.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(246, 108)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setMinimumSize(QtCore.QSize(0, 0))
        Dialog.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.gridLayout_4 = QtWidgets.QGridLayout(Dialog)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.grpFlowMonitorRemovalData = QtWidgets.QGroupBox(Dialog)
        self.grpFlowMonitorRemovalData.setObjectName("grpFlowMonitorRemovalData")
        self.formLayout_4 = QtWidgets.QFormLayout(self.grpFlowMonitorRemovalData)
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_12 = QtWidgets.QLabel(self.grpFlowMonitorRemovalData)
        self.label_12.setObjectName("label_12")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.dte_removal_date = QtWidgets.QDateEdit(self.grpFlowMonitorRemovalData)
        self.dte_removal_date.setCalendarPopup(True)
        self.dte_removal_date.setObjectName("dte_removal_date")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.dte_removal_date)
        self.gridLayout_4.addWidget(self.grpFlowMonitorRemovalData, 0, 0, 1, 1)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem)
        self.btnOK = QtWidgets.QPushButton(Dialog)
        self.btnOK.setObjectName("btnOK")
        self.horizontalLayout_11.addWidget(self.btnOK)
        self.btnCancel = QtWidgets.QPushButton(Dialog)
        self.btnCancel.setObjectName("btnCancel")
        self.horizontalLayout_11.addWidget(self.btnCancel)
        self.gridLayout_4.addLayout(self.horizontalLayout_11, 6, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.grpFlowMonitorRemovalData.setToolTip(_translate("Dialog", "<html><head/><body><p>This is a Random Forest Classifier. This consists of a large number of individual decision trees that operate as an ensemble. Each individual tree in the random forest spits out a class prediction and the class with the most votes becomes our model’s prediction.</p></body></html>"))
        self.grpFlowMonitorRemovalData.setTitle(_translate("Dialog", "Monitor Removal Data:"))
        self.label_12.setText(_translate("Dialog", "Removal Date:"))
        self.btnOK.setText(_translate("Dialog", "OK"))
        self.btnCancel.setText(_translate("Dialog", "Cancel"))
