# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Fergus.Graham\OneDrive - Tetra Tech, Inc\vscode\flowbot_04032024\FlowBot\ui_elements\ui_flowbot_dialog_fsm_set_interim_dates_base.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(228, 121)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.txt_interim_id = QtWidgets.QLineEdit(Dialog)
        self.txt_interim_id.setEnabled(False)
        self.txt_interim_id.setReadOnly(True)
        self.txt_interim_id.setObjectName("txt_interim_id")
        self.gridLayout.addWidget(self.txt_interim_id, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.dte_interim_start = QtWidgets.QDateTimeEdit(Dialog)
        self.dte_interim_start.setCalendarPopup(True)
        self.dte_interim_start.setObjectName("dte_interim_start")
        self.gridLayout.addWidget(self.dte_interim_start, 1, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.dte_interim_end = QtWidgets.QDateTimeEdit(Dialog)
        self.dte_interim_end.setCalendarPopup(True)
        self.dte_interim_end.setObjectName("dte_interim_end")
        self.gridLayout.addWidget(self.dte_interim_end, 2, 1, 1, 1)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem)
        self.btnOK = QtWidgets.QPushButton(Dialog)
        self.btnOK.setObjectName("btnOK")
        self.horizontalLayout_11.addWidget(self.btnOK)
        self.btnCancel = QtWidgets.QPushButton(Dialog)
        self.btnCancel.setObjectName("btnCancel")
        self.horizontalLayout_11.addWidget(self.btnCancel)
        self.gridLayout.addLayout(self.horizontalLayout_11, 3, 0, 1, 2)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Set Date Range"))
        self.label_3.setText(_translate("Dialog", "Interim:"))
        self.label.setText(_translate("Dialog", "Start Date:"))
        self.label_2.setText(_translate("Dialog", "End Date:"))
        self.btnOK.setText(_translate("Dialog", "OK"))
        self.btnCancel.setText(_translate("Dialog", "Cancel"))
