# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Fergus.Graham\OneDrive - Tetra Tech, Inc\vscode\flowbot_04032024\FlowBot\ui_elements\ui_flowbot_dialog_fsm_interim_data_imports_base.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(340, 400)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setMinimumSize(QtCore.QSize(340, 0))
        Dialog.setMaximumSize(QtCore.QSize(340, 16777215))
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.dataImportStatusGroup = QtWidgets.QGroupBox(Dialog)
        self.dataImportStatusGroup.setObjectName("dataImportStatusGroup")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.dataImportStatusGroup)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.statusTable = QtWidgets.QTableWidget(self.dataImportStatusGroup)
        self.statusTable.setObjectName("statusTable")
        self.statusTable.setColumnCount(4)
        self.statusTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.statusTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.statusTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.statusTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.statusTable.setHorizontalHeaderItem(3, item)
        self.statusTable.horizontalHeader().setDefaultSectionSize(100)
        self.statusTable.horizontalHeader().setStretchLastSection(True)
        self.statusTable.verticalHeader().setVisible(False)
        self.verticalLayout_3.addWidget(self.statusTable)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem)
        self.btnOK = QtWidgets.QPushButton(self.dataImportStatusGroup)
        self.btnOK.setObjectName("btnOK")
        self.horizontalLayout_11.addWidget(self.btnOK)
        self.btnCancel = QtWidgets.QPushButton(self.dataImportStatusGroup)
        self.btnCancel.setObjectName("btnCancel")
        self.horizontalLayout_11.addWidget(self.btnCancel)
        self.verticalLayout_3.addLayout(self.horizontalLayout_11)
        self.verticalLayout.addWidget(self.dataImportStatusGroup)
        self.verticalLayout_4.addLayout(self.verticalLayout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        self.dataImportStatusGroup.setTitle(_translate("Dialog", "Data Import Status:"))
        item = self.statusTable.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Site Name"))
        item = self.statusTable.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Data Covers Interim"))
        item = self.statusTable.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Ignore Missing Data"))
        item = self.statusTable.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "Reasons for Missing Data"))
        self.btnOK.setText(_translate("Dialog", "OK"))
        self.btnCancel.setText(_translate("Dialog", "Cancel"))
