# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Fergus.Graham\OneDrive - Tetra Tech, Inc\vscode\flowbot_04032024\FlowBot\ui_elements\ui_flowbot_dialog_fsm_review_classification_base.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1091, 825)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setSizeGripEnabled(True)
        Dialog.setModal(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.plotCanvasReviewClassification = PlotWidget(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plotCanvasReviewClassification.sizePolicy().hasHeightForWidth())
        self.plotCanvasReviewClassification.setSizePolicy(sizePolicy)
        self.plotCanvasReviewClassification.setObjectName("plotCanvasReviewClassification")
        self.horizontalLayout_2.addWidget(self.plotCanvasReviewClassification)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(0, -1, -1, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.chk_classification_acceptable = QtWidgets.QCheckBox(Dialog)
        self.chk_classification_acceptable.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.chk_classification_acceptable.setObjectName("chk_classification_acceptable")
        self.horizontalLayout_3.addWidget(self.chk_classification_acceptable)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.txt_review_comments = QtWidgets.QLineEdit(Dialog)
        self.txt_review_comments.setMinimumSize(QtCore.QSize(350, 0))
        self.txt_review_comments.setObjectName("txt_review_comments")
        self.horizontalLayout_3.addWidget(self.txt_review_comments)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.btnPrevious = QtWidgets.QPushButton(Dialog)
        self.btnPrevious.setObjectName("btnPrevious")
        self.horizontalLayout_3.addWidget(self.btnPrevious)
        self.btnNext = QtWidgets.QPushButton(Dialog)
        self.btnNext.setObjectName("btnNext")
        self.horizontalLayout_3.addWidget(self.btnNext)
        self.horizontalLayout.addLayout(self.horizontalLayout_3)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.btnDone = QtWidgets.QPushButton(Dialog)
        self.btnDone.setObjectName("btnDone")
        self.horizontalLayout_5.addWidget(self.btnDone)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout_5)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.chk_classification_acceptable.setText(_translate("Dialog", "Classification Acceptable"))
        self.label.setText(_translate("Dialog", "Comments:"))
        self.btnPrevious.setText(_translate("Dialog", "Previous"))
        self.btnNext.setText(_translate("Dialog", "Next"))
        self.btnDone.setText(_translate("Dialog", "Done"))
from flowbot_helper import PlotWidget
