# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Fergus.Graham\OneDrive - Tetra Tech, Inc\vscode\Tt_Flowbot\FlowBot\ui_flowbot_dialog_scattergraph_export_base.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setWindowModality(QtCore.Qt.WindowModal)
        Dialog.resize(200, 300)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setMinimumSize(QtCore.QSize(200, 300))
        Dialog.setMaximumSize(QtCore.QSize(200, 300))
        Dialog.setModal(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.lst_FlowMonitors = QtWidgets.QListWidget(Dialog)
        self.lst_FlowMonitors.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.lst_FlowMonitors.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.lst_FlowMonitors.setObjectName("lst_FlowMonitors")
        self.verticalLayout_4.addWidget(self.lst_FlowMonitors)
        self.label_9 = QtWidgets.QLabel(Dialog)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_4.addWidget(self.label_9)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.edtOutputFileSpec = QtWidgets.QLineEdit(Dialog)
        self.edtOutputFileSpec.setStyleSheet("QLineEdit { background: rgb(240, 240, 240) }")
        self.edtOutputFileSpec.setReadOnly(True)
        self.edtOutputFileSpec.setObjectName("edtOutputFileSpec")
        self.horizontalLayout_10.addWidget(self.edtOutputFileSpec)
        self.btnOutput = QtWidgets.QPushButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnOutput.sizePolicy().hasHeightForWidth())
        self.btnOutput.setSizePolicy(sizePolicy)
        self.btnOutput.setMinimumSize(QtCore.QSize(22, 22))
        self.btnOutput.setMaximumSize(QtCore.QSize(22, 22))
        self.btnOutput.setObjectName("btnOutput")
        self.horizontalLayout_10.addWidget(self.btnOutput)
        self.verticalLayout_4.addLayout(self.horizontalLayout_10)
        self.verticalLayout.addLayout(self.verticalLayout_4)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem)
        self.btnOK = QtWidgets.QPushButton(Dialog)
        self.btnOK.setObjectName("btnOK")
        self.horizontalLayout_11.addWidget(self.btnOK)
        self.btnCancel = QtWidgets.QPushButton(Dialog)
        self.btnCancel.setObjectName("btnCancel")
        self.horizontalLayout_11.addWidget(self.btnCancel)
        self.verticalLayout.addLayout(self.horizontalLayout_11)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_9.setText(_translate("Dialog", "Output File Path:"))
        self.btnOutput.setText(_translate("Dialog", "..."))
        self.btnOK.setText(_translate("Dialog", "OK"))
        self.btnCancel.setText(_translate("Dialog", "Cancel"))
