# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\vscode\_qgis_bundled_apps\flowbot_v4_qgis\ui_elements\ui_flowbot_dialog_fsm_merge_raw_data_base.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(832, 638)
        self.verticalLayout_root = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_root.setContentsMargins(12, 12, 12, 12)
        self.verticalLayout_root.setSpacing(10)
        self.verticalLayout_root.setObjectName("verticalLayout_root")
        self.plotCanvasMergeData = PlotWidget(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.plotCanvasMergeData.sizePolicy().hasHeightForWidth())
        self.plotCanvasMergeData.setSizePolicy(sizePolicy)
        self.plotCanvasMergeData.setMinimumSize(QtCore.QSize(600, 350))
        self.plotCanvasMergeData.setObjectName("plotCanvasMergeData")
        self.verticalLayout_root.addWidget(self.plotCanvasMergeData)
        self.horizontalLayout_buttons = QtWidgets.QHBoxLayout()
        self.horizontalLayout_buttons.setObjectName("horizontalLayout_buttons")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_buttons.addItem(spacerItem)
        self.btnOK = QtWidgets.QPushButton(Dialog)
        self.btnOK.setDefault(True)
        self.btnOK.setObjectName("btnOK")
        self.horizontalLayout_buttons.addWidget(self.btnOK)
        self.btnCancel = QtWidgets.QPushButton(Dialog)
        self.btnCancel.setObjectName("btnCancel")
        self.horizontalLayout_buttons.addWidget(self.btnCancel)
        self.verticalLayout_root.addLayout(self.horizontalLayout_buttons)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Merge Raw Data"))
        self.btnOK.setText(_translate("Dialog", "&Merge"))
        self.btnCancel.setText(_translate("Dialog", "Cancel"))
from flowbot_helper import PlotWidget
